name: Deploy to Snowflake Free Trial

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Snowflake cli
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true
          cli-version: "3.11"
          
      - name: test connection
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: snow connection test -x

      - name: Connect and Deploy to Snowflake
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          snowflake_cli connection add --name my_connection \
            --account ${{ env.SNOWFLAKE_ACCOUNT }} \
            --user ${{ env.SNOWFLAKE_USER }} \
            --password ${{ env.SNOWFLAKE_PASSWORD }} \
            --warehouse ${{ env.SNOWFLAKE_WAREHOUSE }} \
            --database ${{ env.SNOWFLAKE_DATABASE }} \
            --role ${{ env.SNOWFLAKE_ROLE }}
          
          # Example: Execute a SQL script
          snowflake_cli sql execute -c my_connection -f ./sql/deploy_objects.sql